# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0004_auto_20170620_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudevent',
            name='event_type',
            field=models.SmallIntegerField(choices=[(1, u'Create'), (2, u'Update'), (3, u'Delete'), (4, u'Many-to-Many Change'), (5, u'Reverse Many-to-Many Change')]),
        ),
    ]
